---
# Example Usage:
# ansible-playbook -i inventory remove_snmpv3.yml -e user=snmpUser2
- hosts: all
  vars:
    # prefix: ''
    prefix: /home/sysadmin/test
  remote_user: sysadmin
  become: yes
  tasks:
  - name: stop snmpd on remote
    service:
      name: snmpd
      state: stopped
  - name: remove createUser <user>...
    lineinfile:
      path: '{{prefix}}/test/var/lib/net-snmp/snmpd.conf'
      regex: '^createUser {{user}}'
      state: absent
      backup: yes
  - name: remove usmUser...<user>
    lineinfile:
      path: '{{prefix}}/var/lib/net-snmp/snmpd.conf'
      regex: '^usmUser*\"{{user}}'
      state: absent
      backup: yes
  - name: remove rwuser <snmp username>
    lineinfile:
      path: '{{prefix}}/etc/snmp/snmpd.conf'
      line: 'rwuser {{user}}'
      state: absent
      backup: yes 
  - name: start snmpd on remote
    service:
      name: snmpd
      state: started
      
