---
# Example Usage:
# ansible-playbook -i inventory add_snmpv3.yml -e user=snmpUser2 -e auth=MD5 -e password=mypassword -e priv=AES -e passphrase=mypassword
- hosts: all
  vars:
    # prefix: ''
    prefix: /home/sysadmin/test
  remote_user: sysadmin
  become: yes
  tasks:
  - name: add rwuser <snmp username>
    lineinfile:
      path: '{{prefix}}/etc/snmp/snmpd.conf' 
      line: 'rwuser {{user}}'
      state: present
      backup: yes 
      
